(defvar mt/my-keyboard-bindings
  '(;;Zoning
    ("C-c `" . zone)
    ("C-c ~" . mt/set-zoning)
    ("C-c !" . zone-leave-me-alone)
    ;;Buffer/Window management
    ("C-x C-b" . ibuffer)
    ("C-x b" . ivy-switch-buffer)
    ("C-x C-f" . counsel-find-file)
    ("C-x C-r" . counsel-recentf)
    ("C-c @" . mt/window-toggle-split-direction)
    ("C-S-<up>" . buf-move-up)
    ("C-S-<down>" . buf-move-down)
    ("C-S-<left>" . buf-move-left)
    ("C-S-<right>" . buf-move-right)
    ("C-c %" . window-shaper-mode)
    ("C-c +" . balance-windows)
    ("C-c ;" . ace-window)
    ;;Text-editing
    ("C-}" . mc/mark-next-like-this)
    ("C-{" . mc/mark-previous-like-this)
    ("C-|" . mc/mark-all-like-this)
    ("C-c #" . display-line-numbers-mode)
    ("C-c _" . outer-spaces-mode)
    ("C-c *" . eagle-eye-mode)
    ("M-/" . undo-tree-visualize)
    ("M-y" . counsel-yank-pop)
    ("M-<down>" . mt/move-line-down)
    ("M-<up>" . mt/move-line-up)
    ("C-<backspace>" . mt/delete-word-backward)
    ("C-c s" . swiper)
    ("C-c ^" . mt/reload-current-file)
    ;;Navigation
    ("C->" . ace-jump-mode)
    ("C-<" . ace-jump-mode-pop-mark)
    ("C-c /" . neotree-toggle)
    ("C-'" . dumb-jump-go)
    ("C-\"" . dumb-jump-back)
    ("C-c C-p s o" . projectile-find-all-occurrences)
    ("C-c C-p s f" . projectile-find-all-references)
    ("C-\\" . wg-switch-to-previous-workgroup)
    ;;Swanking
    ("C-c &" . sublimity-mode)
    ;;Misc
    ("M-x" . counsel-M-x)
    ("C-=" . mt/eval-and-replace)
    ("C-," . myterminal-controls-open-controls)
    ("C-." . emacs-home-show)
    ("C-c |" . wdired-change-to-wdired-mode)
    ("C-c )" . theme-looper-enable-next-theme)
    ("C-c (" . theme-looper-enable-previous-theme)
    ("C-c e" . quickrun)
    ("C-c r" . quickrun-region)
    ("C-c w" . quickrun-replace-region)))

(mapc 'mt/assign-function-to-keys
      mt/my-keyboard-bindings)
